"""init db

Revision ID: 73be563f9f8d
Revises: 
Create Date: 2024-10-10 16:02:56.425905

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73be563f9f8d'
down_revision: str | None = None
branch_labels: str | list[str] | None = None
depends_on: str | list[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_order_uuid'), 'order', ['order_uuid'], unique=True)
    op.create_table('sample',
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('sample_uuid', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ORDERED', 'PROCESSING', 'FAILED', 'PASSED_QC', 'SHIPPED', name='samplestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_index(op.f('ix_sample_order_id'), 'sample', ['order_id'], unique=False)
    op.create_index(op.f('ix_sample_sample_uuid'), 'sample', ['sample_uuid'], unique=True)
    op.create_table('qcresults',
    sa.Column('qc_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('plate_id', sa.Integer(), nullable=False),
    sa.Column('well', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qc_1', sa.Float(), nullable=False),
    sa.Column('qc_2', sa.Float(), nullable=False),
    sa.Column('qc_3', sa.Enum('PASS', 'FAIL', name='qcresult'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.sample_id'], ),
    sa.PrimaryKeyConstraint('qc_id')
    )
    op.create_index(op.f('ix_qcresults_sample_id'), 'qcresults', ['sample_id'], unique=False)
    op.create_table('shipment',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.sample_id'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_index(op.f('ix_shipment_sample_id'), 'shipment', ['sample_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_sample_id'), table_name='shipment')
    op.drop_table('shipment')
    op.drop_index(op.f('ix_qcresults_sample_id'), table_name='qcresults')
    op.drop_table('qcresults')
    op.drop_index(op.f('ix_sample_sample_uuid'), table_name='sample')
    op.drop_index(op.f('ix_sample_order_id'), table_name='sample')
    op.drop_table('sample')
    op.drop_index(op.f('ix_order_order_uuid'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
